print("Hello! Welcome to the band name generator.\nI hear you're having problems coming up with a name for your band.\nLet's help you with that.")
City = input("Which city did you grow up in?\n")
print("Thanks!")
Animal = input("Now, tell me an animal, either a pet or one you like!\n")
print("The name of your band could be " + "The " + City + " " + Animal + "s.")
